//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escola.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EscolaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EscolaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Escola.Domain.Resources.EscolaResource", typeof(EscolaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolaridade atualizada com sucesso!.
        /// </summary>
        public static string EscolaridadeAtualizadaSucesso {
            get {
                return ResourceManager.GetString("EscolaridadeAtualizadaSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolaridade cadastrada com sucesso!.
        /// </summary>
        public static string EscolaridadeCadastradaSucesso {
            get {
                return ResourceManager.GetString("EscolaridadeCadastradaSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolaridade deletada com sucesso!.
        /// </summary>
        public static string EscolaridadeDeletadaSucesso {
            get {
                return ResourceManager.GetString("EscolaridadeDeletadaSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A escolaridade &apos;{0}&apos; não existe na base de dados..
        /// </summary>
        public static string EscolaridadeInformadaNaoExiste {
            get {
                return ResourceManager.GetString("EscolaridadeInformadaNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolaridade não encontrada..
        /// </summary>
        public static string EscolaridadeNaoEncontrada {
            get {
                return ResourceManager.GetString("EscolaridadeNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao tentar executar o comando..
        /// </summary>
        public static string FalhaExecutarComando {
            get {
                return ResourceManager.GetString("FalhaExecutarComando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha interna no servidor:  {0}.
        /// </summary>
        public static string FalhaServidor {
            get {
                return ResourceManager.GetString("FalhaServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O histórico escolar &apos;{0}&apos; já foi cadastrado em outro usuário..
        /// </summary>
        public static string HistoricoJaCadastrado {
            get {
                return ResourceManager.GetString("HistoricoJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sistema não possui escolaridades cadastradas..
        /// </summary>
        public static string NaoExistemEscolaridadesCadastradas {
            get {
                return ResourceManager.GetString("NaoExistemEscolaridadesCadastradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sistema não possui usuários cadastrados..
        /// </summary>
        public static string NaoExistemUsuariosCadastrados {
            get {
                return ResourceManager.GetString("NaoExistemUsuariosCadastrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário atualizado com sucesso!.
        /// </summary>
        public static string UsuarioAtualizadoSucesso {
            get {
                return ResourceManager.GetString("UsuarioAtualizadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário cadastrado com sucesso!.
        /// </summary>
        public static string UsuarioCadastradoSucesso {
            get {
                return ResourceManager.GetString("UsuarioCadastradoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário deletado com sucesso!.
        /// </summary>
        public static string UsuarioDeletadoSucesso {
            get {
                return ResourceManager.GetString("UsuarioDeletadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado..
        /// </summary>
        public static string UsuarioNaoExiste {
            get {
                return ResourceManager.GetString("UsuarioNaoExiste", resourceCulture);
            }
        }
    }
}
